# ID - 2014A7PS160P
# Name - Karan Deep Batra

from assign1 import *
import turtle

print("Option 1 : Display the room environment")
print("Option 2 : Find the path (action sequence) and path cost using T1")
print("Option 3 : Find the path (action sequence) and path cost using T2")
print("Option 4 : Show all results and graphs in the GUI")
var = (int)(input("Enter option number\n"))

if var == 1:
	initialize()
	fillDirt()
	init_screen()
	drawGrid(1)
	drawColumns()
	drawRows()
	drawDirt(1)
	drawLine()
	draw_quadrants()
	drawGrid(2)
	drawColumns()
	drawRows()
	drawDirt(2)
	turtle.exitonclick()

if var == 2:
	initialize()
	fillDirt()
	init_screen()
	drawGrid(1)
	drawColumns()
	drawRows()
	drawDirt(1)
	drawLine()
	draw_quadrants()
	drawGrid(2)
	drawColumns()
	drawRows()
	drawDirt(2)
	calculate_path_uninformed(1)
	write_analysis(1)
	turtle.exitonclick()

if var == 3:
	initialize()
	fillDirt()
	init_screen()
	drawGrid(1)
	drawColumns()
	drawRows()
	drawDirt(1)
	drawLine()
	draw_quadrants()
	drawGrid(2)
	drawColumns()
	drawRows()
	drawDirt(2)
	calculate_path_informed(1)
	write_analysis(2)
	turtle.exitonclick()

if var == 4:
	initialize()
	fillDirt()
	init_screen()
	drawGrid(1)
	drawColumns()
	drawRows()
	drawDirt(1)
	drawLine()
	draw_quadrants()
	drawGrid(2)
	drawColumns()
	drawRows()
	drawDirt(2)
	calculate_path_uninformed(1)
	calculate_path_informed(1)
	write_analysis(3)
	turtle.exitonclick()